### ISSUE TITLE
Node.js Version Issue

### ISSUE THREAD

**Issue by AlexWHughes** [PennazSoftware/homebridge-dmxlight-plugin#13]
Updating to the Homebridge Recommended version of Node.JS presents the following error message in the log

ERROR LOADING PLUGIN homebridge-dmxlight-plugin:
[2/19/2024, 12:46:01 AM] Error: The module '/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/node_modules/dmx-ts/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/node_modules/dmx-ts/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)

**Comment by rahulsainlll** [comment]
plugin is not compatible with the current version of Node.js installed on your system
To resolve this issue:
- You can update the node js
- (if updating Node.js is not an option ) you can reinstall the plugin

 ```bash
npm uninstall homebridge-dmxlight-plugin
npm install homebridge-dmxlight-plugin

**Comment by AlexWHughes** [comment]
Yeah I upgraded to v.2011.1 and it gave me the error. Reinstalling the plugin didn't help via the GUI but the npm package install method did. Thanks!
