### ISSUE TITLE
DMX for dimmer (singe channel)

### ISSUE THREAD

**Issue by markkibble** [PennazSoftware/homebridge-dmxlight-plugin#7]
**Is your feature request related to a problem? Please describe:**
The plugin works a treat with a RGB PAR can I have, address 001 with RGB on channels 1,2 & 3. What I need help on please is how do I control a single DMX channel (for a single monochrome dimmer)? I have a DMX 240v dimmer for traditional lights with 12 channels that run lights in my house, so I need just a single channel to control. I have tried deleting "colorOrder": "rgb" line but the default is Rob so it controls 3 channels. Is there a command for that? 
The command "dmxChannelCount": 1, does not limit control to a single channel as I expected.

**Describe the solution you'd like:**
To be clear I want to have light 1 on DMX channel 1, light 2 on DMX channel 2 etc...

**Describe alternatives you've considered:**
Tried making channel count 1 and removing the RGB .

**Additional context:**
If you can you help with this I would really appreciate it!

This is my config ...

            "name": "DMX Light",
            "platform": "DMXLightHomebridgePlugin",
            "accessories": [
                {
                    "name": "DMX1",
                    "id": "DMX1",
                    "driverName": "enttec-usb-dmx-pro",
                    "serialPortName": "/dev/ttyUSB0",
                    "dmxStartChannel": 1,
                    "dmxChannelCount": 1,
                    "dmxUniverse": 1,
                    "colorOrder": "rgb"
                },
                {
                    "name": "DMX2",
                    "id": "DMX2",
                    "driverName": "enttec-usb-dmx-pro",
                    "serialPortName": "/dev/ttyUSB0",
                    "dmxStartChannel": 2,
                    "dmxChannelCount": 1,
                    "dmxUniverse": 1,
                    "colorOrder": "rgb"
                },
                {
                    "name": "DMX3",
                    "id": "DMX3",
                    "driverName": "enttec-usb-dmx-pro",
                    "serialPortName": "/dev/ttyUSB0",
                    "dmxStartChannel": 3,
                    "dmxChannelCount": 1,
                    "dmxUniverse": 1,
                    "colorOrder": "rgb"
                },
                {
                    "name": "DMX4",
                    "id": "DMX4",
                    "driverName": "enttec-usb-dmx-pro",
                    "serialPortName": "/dev/ttyUSB0",
                    "dmxStartChannel": 4,
                    "dmxChannelCount": 1,
                    "dmxUniverse": 1,
                    "colorOrder": "rgb"
                },
                {
                    "name": "DMX6",
                    "id": "DMX6",
                    "driverName": "enttec-usb-dmx-pro",
                    "serialPortName": "/dev/ttyUSB0",
                    "dmxStartChannel": 6,
                    "dmxChannelCount": 1,
                    "dmxUniverse": 1,
                    "colorOrder": "rgb"
                }

**Comment by PennazSoftware** [comment]
This scenario is not supported. It only works with 3-channel resources…I.e., RGB lights


-Dan

On May 30, 2023, at 12:47 PM, markkibble ***@***.***> wrote:

﻿

Is your feature request related to a problem? Please describe:
The plugin works a treat with a RGB PAR can I have, address 001 with RGB on channels 1,2 & 3. What I need help on please is how do I control a single DMX channel (for a single monochrome dimmer)? I have a DMX 240v dimmer for traditional lights with 12 channels that run lights in my house, so I need just a single channel to control. I have tried deleting "colorOrder": "rgb" line but the default is Rob so it controls 3 channels. Is there a command for that?
The command "dmxChannelCount": 1, does not limit control to a single channel as I expected.

Describe the solution you'd like:
To be clear I want to have light 1 on DMX channel 1, light 2 on DMX channel 2 etc...

Describe alternatives you've considered:
Tried making channel count 1 and removing the RGB .

Additional context:
If you can you help with this I would really appreciate it!

This is my config ...

        "name": "DMX Light",
        "platform": "DMXLightHomebridgePlugin",
        "accessories": [
            {
                "name": "DMX1",
                "id": "DMX1",
                "driverName": "enttec-usb-dmx-pro",
                "serialPortName": "/dev/ttyUSB0",
                "dmxStartChannel": 1,
                "dmxChannelCount": 1,
                "dmxUniverse": 1,
                "colorOrder": "rgb"
            },
            {
                "name": "DMX2",
                "id": "DMX2",
                "driverName": "enttec-usb-dmx-pro",
                "serialPortName": "/dev/ttyUSB0",
                "dmxStartChannel": 2,
                "dmxChannelCount": 1,
                "dmxUniverse": 1,
                "colorOrder": "rgb"
            },
            {
                "name": "DMX3",
                "id": "DMX3",
                "driverName": "enttec-usb-dmx-pro",
                "serialPortName": "/dev/ttyUSB0",
                "dmxStartChannel": 3,
                "dmxChannelCount": 1,
                "dmxUniverse": 1,
                "colorOrder": "rgb"
            },
            {
                "name": "DMX4",
                "id": "DMX4",
                "driverName": "enttec-usb-dmx-pro",
                "serialPortName": "/dev/ttyUSB0",
                "dmxStartChannel": 4,
                "dmxChannelCount": 1,
                "dmxUniverse": 1,
                "colorOrder": "rgb"
            },
            {
                "name": "DMX6",
                "id": "DMX6",
                "driverName": "enttec-usb-dmx-pro",
                "serialPortName": "/dev/ttyUSB0",
                "dmxStartChannel": 6,
                "dmxChannelCount": 1,
                "dmxUniverse": 1,
                "colorOrder": "rgb"
            }

**Comment by markkibble** [comment]
Thanks for coming back Dan.That's a pity as it was going to be a central plank in my home automation setup. How much coding would it be to strip it down to work with single channel unit? Is this something you could do?Kind regardsMark Kibble+44 7790493897On 7 Jun 2023, at 19:52, Pennaz ***@***.***> wrote:﻿
This scenario is not supported. It only works with 3-channel resources…I.e., RGB lights





-Dan



On May 30, 2023, at 12:47 PM, markkibble ***@***.***> wrote:



﻿



Is your feature request related to a problem? Please describe:

The plugin works a treat with a RGB PAR can I have, address 001 with RGB on channels 1,2 & 3. What I need help on please is how do I control a single DMX channel (for a single monochrome dimmer)? I have a DMX 240v dimmer for traditional lights with 12 channels that run lights in my house, so I need just a single channel to control. I have tried deleting "colorOrder": "rgb" line but the default is Rob so it controls 3 channels. Is there a command for that?

The command "dmxChannelCount": 1, does not limit control to a single channel as I expected.



Describe the solution you'd like:

To be clear I want to have light 1 on DMX channel 1, light 2 on DMX channel 2 etc...



Describe alternatives you've considered:

Tried making channel count 1 and removing the RGB .



Additional context:

If you can you help with this I would really appreciate it!



This is my config ...



        "name": "DMX Light",

        "platform": "DMXLightHomebridgePlugin",

        "accessories": [

            {

                "name": "DMX1",

                "id": "DMX1",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 1,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            },

            {

                "name": "DMX2",

                "id": "DMX2",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 2,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            },

            {

                "name": "DMX3",

                "id": "DMX3",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 3,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            },

            {

                "name": "DMX4",

                "id": "DMX4",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 4,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            },

            {

                "name": "DMX6",

                "id": "DMX6",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 6,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            }

**Comment by markkibble** [comment]
Hi, I wonder if you wrote this enhancement could you licence it so I could pay you?

**Comment by markkibble** [comment]
Hi Dan Again

I wondered if your wrote the enhancement if there is a way I could pay you for it? Like a licence fee or something?

Thanks

Mark

**Comment by PennazSoftware** [comment]
I’m heading out on vacation for 3 weeks but will look into this when I return. Can you provide me more details about the one channel?  Does it take a variable value (I.e., 0-255) or is it just 0 or 1?  Also, what is the name of the device?  Better yet, if you can provide me with product name and model that might be more helpful.

-Dan

On Jun 13, 2023, at 1:42 PM, markkibble ***@***.***> wrote:

﻿

Hi Dan Again

I wondered if your wrote the enhancement if there is a way I could pay you for it? Like a licence fee or something?

Thanks

Mark

**Comment by markkibble** [comment]
Hi Dan

Thanks for reaching out. 

There are many single and multi-channel 110/240vac  dimmers on the market, they are traditionally used in theatres and commercial buildings.  They comprise DMX decoder, with each channel (sequential) running a single fader 0-255 being 0-100%. (So not a single lamp device with multiple channels for RGB, Flash, Master fade etc..) 

Typical units are 4 or 6 channel, so each dimmer channel corresponds to the next DMX address, with the start address being programable. These units are readily available second hand on ebay and make excellent retrofits for a house.  The great thing is that there is no need to get involved in mains wiring of triacs etc.  so it’s nice and safe and great for hobbiests.

In my home automation system I have an Anytronics unit like this photo. It is 16 channel, so 16 dimmers in total, address 1-16 (or whatever the start address is +16) . Each channel needs a name and 0-255 to control it.  As such you could set up each channel as a separate device to control in Homebrideg/Homekit, or have a device with multiple channels...

So;
Channel 1 - Dimmer ! - DMX Address 001 > 0-255
Channel 2 - Dimmer 2 -DMX Address 002 >  0-255
Channel 3 - Dimmer 3 - DMX Address 003 > 0-255
Channel 4 - Dimmer 4 - DMX Address 004 > 0-255
Etc..

Obviously the start address could be anything from 0-255 so you could have multiple units, or indeed some RGB units at higher addresses.

I’m happy to test anything you do and, as I said, happy to pay a licence or contribute.

Thanks again for your help.

Mark


 


https://anytronics.co.uk/rack-mounted-dimmers.html
https://anytronics.co.uk/wall-mounted-dimmers.html

**Comment by PennazSoftware** [comment]
I made a change to support a single channel and it is now available in Homebridge. You will need to modify the colorOrder setting to "w". 
Please let me know if this works for you. 
-Dan

**Comment by markkibble** [comment]
Hi Dan

Thanks for making the change.  I have installed the update - it installs fine and boots.  I then I update the JSON to include the accessory and changed the “ColorOrder to “w” as below.



{
    "name": "DMX Light",
    "platform": "DMXLightHomebridgePlugin",
    "accessories": [
        {
            "name": "White Fader",
            "id": "WF",
            "driverName": "enttec-usb-dmx-pro",
            "serialPortName": "/dev/ttyUSB0",
            "dmxStartChannel": 1,
            "dmxChannelCount": 1,
            "dmxUniverse": 1,
            "colorOrder": "w"
        }
    ]
}

And I get the error message below - ‘Got SIGTERM, shouting down Homebridge ...the Homebridge server fails to start.  Any ideas?

M


gin/src/platform.ts:31:12)
    at HomebridgeAPI.emit (node:events:525:35)
    at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:190:14)
[24/07/2023, 14:22:14] [DMX Light] successfully added universe for Enttec Pro
[24/07/2023, 14:22:14] Got SIGTERM, shutting down Homebridge...
[24/07/2023, 14:22:15] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:513:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[24/07/2023, 14:22:15] [RPi] hardware: Raspberry Pi 4B 1.5 (4GB)
[24/07/2023, 14:22:15] [RPi] os: Raspbian GNU/Linux 11 (bullseye) [32 bit]
[24/07/2023, 14:22:15] [RPi] restored 3 accessories from cache

**Comment by PennazSoftware** [comment]
Couple of things.

1. I totally missed the fact you were using Enttec Pro instead of SACN. I had previously made the change to SACN.  I just added support for the Entecc Pro.  I no longer have easy access to an Enttec Pro device so I'm flying blind here.
2. I'm not sure why you are getting the other error. Did you get past this point with previous releases?  If so, try changing the 'name' and 'id' fields and restart.  Let me know if this continues.

**Comment by PennazSoftware** [comment]
I forgot to mention that I posted a new build today...so give that a try.

**Comment by markkibble** [comment]
Hi Dan

Thanks for the this and sorry not to be clear that I was using an Enttec Pro!

I’ve tried again, I have added the accessory as per below json - it is accepted but then reboot of Homebrideg results in errors see below:

‘Unsupported colour order’ appears to be an issue - I still ge the SIGTERM error.

{
    "name": "DMX Light",
    "platform": "DMXLightHomebridgePlugin",
    "accessories": [
        {
            "name": "Fader",
            "id": "Fader",
            "driverName": "enttec-usb-dmx-pro",
            "serialPortName": "/dev/ttyUSB0",
            "dmxStartChannel": 1,
            "dmxChannelCount": 1,
            "dmxUniverse": 1,
            "colorOrder": "w"
        }
    ]
}


If I take the ‘Accessories section’ out of the json it boots OK - but obviously of no use?  Note that with the “rgb” option selected my system fails to boot. This is after reinstalling your plugin so we seem to have gone backwards as I could get my 12 channel dimmer unit working on a single RGB config, where Channel 1, 2 & 3 come up as R, G and B selected in HomeKit. before.

Any ideas?

Thanks so much

Mark


Homebridge boot log…...

[31/07/2023, 12:52:58] [eWeLink] Plugin initialised. Setting up accessories....
[31/07/2023, 12:52:58] [DMX Light] An unsupported color order was found. Now using default of "rgb".
[31/07/2023, 12:52:58] [DMX Light] Adding new accessory: Fader
[31/07/2023, 12:52:58] RangeError: universe should be in the range [1-63999]
    at FrameLayer.setUniverse (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/node_modules/e131/lib/e131/frame_layer.js:116:11)
    at Packet.setUniverse (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/node_modules/e131/lib/e131/packet.js:165:20)
    at new SacnUniverse (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/src/sacnUniverse.ts:27:23)
    at new DmxController (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/src/dmx.ts:35:29)
    at new DMXLightPlatformAccessory (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/src/platformAccessory.ts:59:26)
    at DMXLightHomebridgePlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/src/platform.ts:174:9)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-dmxlight-plugin/src/platform.ts:31:12)
    at HomebridgeAPI.emit (node:events:525:35)
    at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:190:14)
[31/07/2023, 12:52:58] [DMX Light] successfully added universe for Enttec Pro
[31/07/2023, 12:52:58] Got SIGTERM, shutting down Homebridge...
[31/07/2023, 12:52:58] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:513:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[31/07/2023, 12:53:00] [Ring] Found the following locations:
[31/07/2023, 12:53:00] [Ring]   locationId: d66aca44-6161-4789-a45f-206673c286e6 - Reading
[31/07/2023, 12:53:00] [eWeLink] Fetching devices from eWeLink home/id [My Home] [5eea94b58ebef40007463290].
[31/07/2023, 12:53:00] [Ring] Configuring 1 cameras and 2 devices for location "Reading" - locationId: d66aca44-6161-4789-a45f-206673c286e6



Mark Kibble
+44 7790 493897

**Comment by markkibble** [comment]
Hi Dan

Have you had the chance to look at this at all? I would really appreciate it if you can get it working.  I’m happy to test anything with my Enttec Pro.

Thanks

M

**Comment by jlg89** [comment]
All 15 of my fixtures are fade-only single channel, and my plugin config has them all in there as single-channel. All on sACN. I expect issues with channels that overlap what the plugin expects to be a three-channel fixture -- e.g. if I send commands to the fixture at address 17, I would expect odd issues with fixtures 18-19. However, if I control any single fixture with the plugin, every other fixture goes to zero.

**Comment by jlg89** [comment]
I could be wrong here, but I think the issue may be that, in dmx.ts, each fixture is treated as its own universe, even when multiple fixtures have the same universe number. IOW the plugin needs to figure out how many different universes are in the config, then group fixtures from the config in their particular universes, then create a "master buffer" for each distinct universe, then when updating a fixture, just update the relevant channels in the "master buffer" for that fixture definition and leave the rest of the channels alone.

I've forked a version of the code, but I'm not (yet) familiar enough with TypeScript to figure out how to fix this.

**Comment by markkibble** [comment]
Hi Dan

Have you had the chance to look at this at all? I would really appreciate it if you can get it working.  I’m happy to test anything with my Enttec Pro.

Thanks

M

**Comment by PennazSoftware** [comment]
I just published a fix for Enttec Pro. I had to dig up one of these devices and it was failing on initialization. I didn’t have any lights to use with it so couldn’t test that aspect.

-Dan

On Oct 1, 2023, at 5:04 AM, markkibble ***@***.***> wrote:

﻿

Hi Dan

Have you had the chance to look at this at all? I would really appreciate it if you can get it working. I’m happy to test anything with my Enttec Pro.

Thanks

M

**Comment by PennazSoftware** [comment]
I just posted a fix. Let me know if that works. There is a buffer in the SACN class that should be the same size as the channel count.  It was set to 512 so each command was overwriting the next.

-Dan

On Sep 23, 2023, at 3:45 PM, jlg89 ***@***.***> wrote:

﻿

I could be wrong here, but I think the issue may be that, in dmx.ts, each fixture is treated as its own universe, even when multiple fixtures have the same universe number. IOW the plugin needs to figure out how many different universes are in the config, then group fixtures from the config in their particular universes, then create a "master buffer" for each distinct universe, then when updating a fixture, just update the relevant channels in the "master buffer" for that fixture definition and leave the rest of the channels alone.

I've forked a version of the code, but I'm not (yet) familiar enough with TypeScript to figure out how to fix this.

**Comment by jlg89** [comment]
Thank you so much for taking a look at this! I'm out of pocket for another week or so, but will try the updated plugin as soon as I can. If/when you have time, take a look at my forked code, specifically what I did with using "colorOrder=w" in the sACN parts, and see what you think. When reading current state I pull in that single value as "R" and then duplicate it to G and B (so gradient transition calculations work), and when generating a DMX update, I only send the R value. So the code basically treats single-channel as standard RGB internally. I also adjusted the FadeIn code so it should work for any fade operation -- up, down, in, or out, and eliminated the FadeOut section.

Again, I'm just getting into TS coding, so check my work for stupid mistakes.

**Comment by markkibble** [comment]
Hi Dan

Thanks so much for the fix, it is loading up OK now with an Enttec Pro.  I think we are nearly there!.

When I configured just one light, start address DMX 1 with colour order 'w', so it should control just that single DMAX address  0-255. What it actually controls addresses 1,2 &3, as if it was an RGB.  I trust I am not misinterpreting your setup instructions for config or is there still a small bug? 

As I explained, I have a 16 channel DMX dimmer, with start address of 1. So each light is then individually addressed from 1-16 address.

This means I can have light 1 = DMX address 1, dimmer 0-155, Light 2 DMX address 2 , dimmer 0-225 etc.. Config below (for just 2).  Can you confirm I am doing it correctly or is there just a small problem?

Thanks, M

{
            "name": "DMX Light",
            "platform": "DMXLightHomebridgePlugin",
            "accessories": [
                {
                    "name": "Demo Dimmer 1",
                    "id": "DIM1",
                    "driverName": "enttec-usb-dmx-pro",
                    "serialPortName": "/dev/ttyUSB0",
                    "dmxStartChannel": 1,
                    "dmxChannelCount": 1,
                    "dmxUniverse": 1,
                    "colorOrder": "w"
                },
                {
                    "name": "Demo Dimmer2",
                    "id": "DIM2",
                    "driverName": "enttec-usb-dmx-pro",
                    "serialPortName": "/dev/ttyUSB0",
                    "dmxStartChannel": 2,
                    "dmxChannelCount": 1,
                    "dmxUniverse": 1,
                    "colorOrder": "w"
                }
            ]
        }

**Comment by jlg89** [comment]
Check your log file to see if the plugin is throwing an error at startup when it sees the colorOrder value of "w" and defaulting it to rgb. That's one thing I fixed in the pull request. At least, I think I fixed it. Look at the changes in platform.ts.

**Comment by PennazSoftware** [comment]
Okay. 😀.  The color order support for “w” that I added is specific to the SACN configuration. The Enttec Pro utilizes a different library for controlling it so I’ll need to configure that.  I’m heading to a golf tournament on Friday and then Mexico for a week so hopefully I can find time before I go.

-Dan

On Oct 3, 2023, at 12:42 PM, markkibble ***@***.***> wrote:

﻿

Hi Dan

Thanks so much for the fix, it is loading up OK now with an Enttec Pro. I think we are nearly there!.

When I configured just one light, start address DMX 1 with colour order 'w', so it should control just that single DMAX address 0-255. What it actually controls addresses 1,2 &3, as if it was an RGB. I trust I am not misinterpreting your setup instructions for config or is there still a small bug?

As I explained, I have a 16 channel DMX dimmer, with start address of 1. So each light is then individually addressed from 1-16 address.

This means I can have light 1 = DMX address 1, dimmer 0-155, Light 2 DMX address 2 , dimmer 0-225 etc.. Config below (for just 2). Can you confirm I am doing it correctly or is there just a small problem?

Thanks, M

{
"name": "DMX Light",
"platform": "DMXLightHomebridgePlugin",
"accessories": [
{
"name": "Demo Dimmer 1",
"id": "DIM1",
"driverName": "enttec-usb-dmx-pro",
"serialPortName": "/dev/ttyUSB0",
"dmxStartChannel": 1,
"dmxChannelCount": 1,
"dmxUniverse": 1,
"colorOrder": "w"
},
{
"name": "Demo Dimmer2",
"id": "DIM2",
"driverName": "enttec-usb-dmx-pro",
"serialPortName": "/dev/ttyUSB0",
"dmxStartChannel": 2,
"dmxChannelCount": 1,
"dmxUniverse": 1,
"colorOrder": "w"
}
]
}

**Comment by markkibble** [comment]
Thanks Dan, happy to test any reconfig work, at least I know It’s not me being dumb!

Enjoy your break whatever!

M

**Comment by jlg89** [comment]
FWIW, the changes I made don't touch the Enttec code, just the sACN stuff, though the change in platform.ts should make single-channel work properly for Enttec -- still no transitions, though.

**Comment by markkibble** [comment]
Hi Dan, I trust you had a good vacation.

Is it possible to do the config work so I can test the code with an Enttec Pro?

M

**Comment by jlg89** [comment]
Trying 1.2.6, all my sACN fixtures give this error, and nothing works:

10/22/2023, 10:47:55 PMDMX Lighting BridgeDMX LightAn unsupported color order was found. Now using default of "rgb".

**Comment by markkibble** [comment]
Hi Dan, 

Sorry t hassle you but Is it possible to do the config work so I can test the code with an Enttec Pro?

Thanks!

M

**Comment by markkibble** [comment]
Hi Dan,  I guess you are busy but I really want to get this working with an Enttec Pro, as I said I'm happy to do testing. Can you find time to try and fix this code please?  

Really appreciate it !  Mark

**Comment by PennazSoftware** [comment]
Sorry, I have been traveling and not near my computer where the lighting controllers are. I’ll be back next weekend.

-Dan

On Nov 12, 2023, at 9:58 AM, markkibble ***@***.***> wrote:

﻿

Hi Dan, I guess you are busy but I really want to get this working with an Enttec Pro, as I said I'm happy to do testing. Can you find time to try and fix this code please?

Really appreciate it ! Mark

**Comment by markkibble** [comment]
Thanks DanI'm travelling too so no problem!Kind regardsMark Kibble+44 7790493897On 21 Nov 2023, at 23:07, Pennaz ***@***.***> wrote:﻿
Sorry, I have been traveling and not near my computer where the lighting controllers are. I’ll be back next weekend.



-Dan



On Nov 12, 2023, at 9:58 AM, markkibble ***@***.***> wrote:



﻿



Hi Dan, I guess you are busy but I really want to get this working with an Enttec Pro, as I said I'm happy to do testing. Can you find time to try and fix this code please?



Really appreciate it ! Mark

**Comment by markkibble** [comment]
Hi Dan, I'm back from vacation.  Just wondered if you had had a chance to look at this?

Thanks, M

**Comment by markkibble** [comment]
Hi Dan, sorry to hassle but can you find a bit of time to do this enhancement of the holidays please?  It would be very much appreciated.  Have a great Christmas!  Mark in the UK

**Comment by markkibble** [comment]
Hi Dan, Happy New Year to you!

Sorry to chase but it would be great if you could take a quick look at this? Rest of my home automation is great but I do need this to run a number of lights. I would really appreciate it fixing.

Thanks

Mark

**Comment by PennazSoftware** [comment]
I’m having a hard time getting to this. I started a new job.  I’m thinking about opening it up so people can make their own changes to the code.

-Dan

On Jan 3, 2024, at 9:04 AM, markkibble ***@***.***> wrote:

﻿

Hi Dan, Happy New Year to you!

Sorry to chase but it would be great if you could take a quick look at this? Rest of my home automation is great but I do need this to run a number of lights. I would really appreciate it fixing.

Thanks

Mark

**Comment by markkibble** [comment]
Hi DanThanks for getting back.I appreciate new jobs mean loads of extra commitment so I understand the issue. Not sure if opening it up go but any progress would be appreciated. I was under the impression that it was only a few tweaks? Is it possible just to do that first? I'm not a coder myself so reliant on others so  I  can't help other than test the results!Kind regardsMark Kibble+44 7790493897On 20 Jan 2024, at 06:51, Pennaz ***@***.***> wrote:﻿
I’m having a hard time getting to this. I started a new job.  I’m thinking about opening it up so people can make their own changes to the code.



-Dan



On Jan 3, 2024, at 9:04 AM, markkibble ***@***.***> wrote:



﻿



Hi Dan, Happy New Year to you!



Sorry to chase but it would be great if you could take a quick look at this? Rest of my home automation is great but I do need this to run a number of lights. I would really appreciate it fixing.



Thanks



Mark

**Comment by markkibble** [comment]
Hi DanJust wondered if your circumstances have changed and you had time to tweak this plugin as I discussed?Kind regardsMark Kibble+44 7790493897On 8 Jun 2023, at 09:57, ***@***.*** wrote:﻿Thanks for coming back Dan.That's a pity as it was going to be a central plank in my home automation setup. How much coding would it be to strip it down to work with single channel unit? Is this something you could do?Kind regardsMark Kibble+44 7790493897On 7 Jun 2023, at 19:52, Pennaz ***@***.***> wrote:﻿
This scenario is not supported. It only works with 3-channel resources…I.e., RGB lights





-Dan



On May 30, 2023, at 12:47 PM, markkibble ***@***.***> wrote:



﻿



Is your feature request related to a problem? Please describe:

The plugin works a treat with a RGB PAR can I have, address 001 with RGB on channels 1,2 & 3. What I need help on please is how do I control a single DMX channel (for a single monochrome dimmer)? I have a DMX 240v dimmer for traditional lights with 12 channels that run lights in my house, so I need just a single channel to control. I have tried deleting "colorOrder": "rgb" line but the default is Rob so it controls 3 channels. Is there a command for that?

The command "dmxChannelCount": 1, does not limit control to a single channel as I expected.



Describe the solution you'd like:

To be clear I want to have light 1 on DMX channel 1, light 2 on DMX channel 2 etc...



Describe alternatives you've considered:

Tried making channel count 1 and removing the RGB .



Additional context:

If you can you help with this I would really appreciate it!



This is my config ...



        "name": "DMX Light",

        "platform": "DMXLightHomebridgePlugin",

        "accessories": [

            {

                "name": "DMX1",

                "id": "DMX1",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 1,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            },

            {

                "name": "DMX2",

                "id": "DMX2",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 2,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            },

            {

                "name": "DMX3",

                "id": "DMX3",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 3,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            },

            {

                "name": "DMX4",

                "id": "DMX4",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 4,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            },

            {

                "name": "DMX6",

                "id": "DMX6",

                "driverName": "enttec-usb-dmx-pro",

                "serialPortName": "/dev/ttyUSB0",

                "dmxStartChannel": 6,

                "dmxChannelCount": 1,

                "dmxUniverse": 1,

                "colorOrder": "rgb"

            }
